title: "🇺🇦 Andrii Liashenko"
tagline: "Andrii Liashenko | Software Engineer's blog about distributed systems, AWS, architecture."
description: "Andrii Liashenko is a Software Engineer with 6+ years of experience. Currently working at Datadog on CI Observability. Before worked at Amazon and Snap. Experienced in Backend development, Cloud, AWS, Distributed systems, Databases, DevOps, CI/CD."
author: Andrii Liashenko
email: ndrlyashenko@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/avatar.jpeg'
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-157153688-1

# Social
social:
  twitter: https://twitter.com/ndrlyashenko
  twitter_username: ndrlyashenko
  github: https://github.com/liashenko
  linkedin: https://www.linkedin.com/in/andriiliashenko/
  youtube: https://www.youtube.com/@andrii.liashenko

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives